### ISSUE TITLE
An item with same key has already been created

### ISSUE THREAD

**Issue by rohit3d2003** [ExcelDataReader/ExcelDataReader#128]
I am importing multiple excel files in paralle and while creating the excelReader object I am receiving the error.

**Code**

using (var excelReader = Path.GetExtension(input.FileName) == ".xls"
                        ? ExcelReaderFactory.CreateBinaryReader(stream)
                        : ExcelReaderFactory.CreateOpenXmlReader(stream))
                    {
**Error**
System.ArgumentException occurred
  HResult=-2147024809
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at Excel.Log.LogManager.Log(String objectName) in c:\development\ExcelDataReader\Excel\Log\LogManager.cs:line 48
       at Excel.Log.LogManager.Log[T](T type) in c:\development\ExcelDataReader\Excel\Log\LogManager.cs:line 28
       at Excel.Core.ZipWorker.NewTempPath() in c:\development\ExcelDataReader\Excel\Core\ZipWorker.cs:line 248
       at Excel.Core.ZipWorker.Extract(Stream fileStream) in c:\development\ExcelDataReader\Excel\Core\ZipWorker.cs:line 84
       at Excel.ExcelOpenXmlReader.Initialize(Stream fileStream) in c:\development\ExcelDataReader\Excel\ExcelOpenXmlReader.cs:line 333
       at Excel.ExcelReaderFactory.CreateOpenXmlReader(Stream fileStream) in c:\development\ExcelDataReader\Excel\ExcelReaderFactory.cs:line 74
       at Paragon.Service.ImportService.ImportVacationTracker(ImportFileModel input) in C:\Projects\Paragon\Paragon\Service\ImportService.cs:line 666
  InnerException:

**Comment by thriolsson** [comment]
May I assume that you use the NuGet package? That version is quite old and contains a bug that causes this error. It has since been in the source code. See #122.

**Comment by rohit3d2003** [comment]
The version I have is 2.1.2.3 and I got it from Nuget. Is the issue fixed?

**Comment by thriolsson** [comment]
The issue should be fixed in the source code here on GitHub, but as far as I can tell there has been no new NuGet package for years.

**Comment by rohit3d2003** [comment]
I took latest from Nuget project and added the Dll's. Now the data read is in different language. Not sure what's going on

I have added Excel.dll and ICSharpCode.SharpZipLib.dll

**Comment by thriolsson** [comment]
I am not sure what you mean by "different language". If you refer to date and time formats, I think this is controlled by the current culture settings of your thread.

**Comment by rohit3d2003** [comment]
While reading the excel file some of the cells contains garbage value:

![image](https://cloud.githubusercontent.com/assets/16943885/16046475/31b6a17c-3212-11e6-9882-0dffbe17c53c.png)

This works fine if I used earlier version of ExcelDataReader straight out of code plex

**Comment by wizardgsz** [comment]
Hi @rohit3d2003, did you verified latest [develop build](https://github.com/ExcelDataReader/ExcelDataReader/archive/develop.zip) meanwhile?
Let me know if I can help you to solve your issue.
Are you using "phonetic strings" in cells?
Thanks a lot
