### ISSUE TITLE
Certain sized XLS workbooks throw ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by ryan-bunker** [ExcelDataReader/ExcelDataReader#184]
XLS Workbooks of a certain size throw an `ArgumentOutOfRangeException` when calling `Excel.ExcelReaderFactory.CreateBinaryReader`.
```
System.ArgumentOutOfRangeException: Stream length must be non-negative and less than 2^31 - 1 - origin.
Parameter name: offset
       at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
       at Excel.Core.BinaryFormat.XlsFat..ctor(XlsHeader hdr, List`1 sectors, Int32 sizeOfSector, Boolean isMini, XlsRootDirectory rootDir) in c:\development\ExcelDataReader\Excel\Core\BinaryFormat\XlsFat.cs:line 52
       at Excel.Core.BinaryFormat.XlsHeader.get_FAT() in c:\development\ExcelDataReader\Excel\Core\BinaryFormat\XlsHeader.cs:line 232
       at Excel.Core.BinaryFormat.XlsStream..ctor(XlsHeader hdr, UInt32 startSector, Boolean isMini, XlsRootDirectory rootDir) in c:\development\ExcelDataReader\Excel\Core\BinaryFormat\XlsStream.cs:line 22
       at Excel.Core.BinaryFormat.XlsRootDirectory..ctor(XlsHeader hdr) in c:\development\ExcelDataReader\Excel\Core\BinaryFormat\XlsRootDirectory.cs:line 19
       at Excel.ExcelBinaryReader.readWorkBookGlobals() in c:\development\ExcelDataReader\Excel\ExcelBinaryReader.cs:line 161
       at Excel.ExcelBinaryReader.Initialize(Stream fileStream) in c:\development\ExcelDataReader\Excel\ExcelBinaryReader.cs:line 914
       at Excel.ExcelReaderFactory.CreateBinaryReader(Stream fileStream, Boolean convertOADate) in c:\development\ExcelDataReader\Excel\ExcelReaderFactory.cs:line 47
```

I've included an example workbook that reproduces the issue.

[ArgumentOutOfRangeException-Workbook.xls.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/685825/ArgumentOutOfRangeException-Workbook.xls.zip)

**Comment by ryan-bunker** [comment]
Further research shows that this only happens if `CreateBinaryReader` is called with a `System.IO.MemoryStream`. This is because `MemoryStream` doesn't support seeking past the end of the stream.

**Comment by ryan-bunker** [comment]
The root of the issue is in `XlsHeader.cs` when reading the last value of the last DIFAT sector. If the workbook requires additional DIFAT sectors beyond what is stored in the header and the last additional DIFAT sector is EXACTLY full (no entries marked with `FAT_FreeSpace`) then the `FAT_EndOfChain` value at the end of the sector is mistakenly read as an additional FAT sector.

This causes (later, in `XlsFat.cs`) an attempt to seek to `0xFFFFFFFE` (`EndOfChain`) which causes the exception for a MemoryStream (FileStream allows seeking this far, but the subsequent call to `Read` reads no bytes and we append a second copy of `buff` to `ms` again, although this doesn't seem to cause any issues).

This only happens on certain sized workbooks because if the layout causes any of the entries in the additional DIFAT sectors to be marked `FAT_FreeSpace` then we bail early before we add the erroneous value into the sector list.

I coded the fix to ignore this value if it isn't a valid regular sector although this was only to limit impact as according to the spec (see https://msdn.microsoft.com/en-us/library/dd942138.aspx?f=255&MSPPError=-2147217396) this value should always be `0xFFFFFFFE` (`FAT_EndOfChain`) for the last additional DIFAT sector (and thus should never be considered a real sector to read from).
