### ISSUE TITLE
IExcelDataReader.GetString throws a NullReferenceException if nothing has been read yet

### ISSUE THREAD

**Issue by hughbe** [ExcelDataReader/ExcelDataReader#240]
```cs
using (IExcelDataReader reader = ExcelReaderFactory.CreateReader(anyXMLStream))
{
    var columnNames = new Dictionary<string, int>(reader.FieldCount);
    for (int columnIndex = 0; columnIndex < reader.FieldCount; columnIndex++)
    {
        string name = reader.GetString(columnIndex);
        columnNames.Add(name, columnIndex);
    }

    return columnNames;
}
```

Stack trace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ExcelDataReader.ExcelDataReader`2.GetString(Int32 i)
   at Isaf.Importer.IsafImporter.GetColumnMappings(IExcelDataReader reader) in C:\Users\hugh\Documents\GitHub\isaf-demand-side\src\backend\Isaf.Importer\IsafImporter.cs:line 72
   at Isaf.Importer.IsafImporter.<ReadRows>d__6.MoveNext() in C:\Users\hugh\Documents\GitHub\isaf-demand-side\src\backend\Isaf.Importer\IsafImporter.cs:line 48
   at Isaf.Importer.IsafImporter.ReadTraining(IExcelDataReader reader) in C:\Users\hugh\Documents\GitHub\isaf-demand-side\src\backend\Isaf.Importer\IsafImporter.cs:line 38
   at Isaf.Importer.IsafImporter.PerformImport() in C:\Users\hugh\Documents\GitHub\isaf-demand-side\src\backend\Isaf.Imp
```

**Comment by andersnm** [comment]
Thanks, this fits nicely together with #239. A quick googling hints at SqlDataReader/OleDbDataReader throws an InvalidOperationException() in these cases, which arguably is more accurate than NullReferenceException.
