### ISSUE TITLE
Exception : Same key has already been added is coming while reading the .xlsx files.

### ISSUE THREAD

**Issue by Vanshita** [ExcelDataReader/ExcelDataReader#243]
An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Excel.Log.LogManager.Log(String objectName) in c:\development\ExcelDataReader\Excel\Log\LogManager.cs:line 48
   at Excel.Log.LogManager.Log[T](T type) in c:\development\ExcelDataReader\Excel\Log\LogManager.cs:line 28
   at Excel.Core.ZipWorker.NewTempPath() in c:\development\ExcelDataReader\Excel\Core\ZipWorker.cs:line 248
   at Excel.Core.ZipWorker.Extract(Stream fileStream) in c:\development\ExcelDataReader\Excel\Core\ZipWorker.cs:line 84
   at Excel.ExcelOpenXmlReader.Initialize(Stream fileStream) in c:\development\ExcelDataReader\Excel\ExcelOpenXmlReader.cs:line 333
   at TaskParallelism.Program.Read(Int32 threadId) in C:\Users\vtilwani\Downloads\HighCPU_new\HighCPU_new\TaskParallelism\Program.cs:line 303

**Comment by appel1** [comment]
This is afaik fixed in the 3.0 pre-release.

**Comment by andersnm** [comment]
Yes, this is fixed. See also #122
