### ISSUE TITLE
System.IO.FileLoadException: Could not load file or assembly 'System.IO.Compression

### ISSUE THREAD

**Issue by raphaelaubin** [ExcelDataReader/ExcelDataReader#337]
Hi,

I'm having this exception:
System.IO.FileLoadException: Could not load file or assembly 'System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT : 0x80131040)

when this line is executed:
`using (var reader = ExcelReaderFactory.CreateReader(stream)) {`

Complete code
`private DataSet ExtractDataFromExcelFile(String pFilePath) {
            DataSet dataset = null;

            using (var stream = File.Open(pFilePath, FileMode.Open, FileAccess.Read)) {
                // Auto-detect format, supports:
                //  - Binary Excel files (2.0-2003 format; *.xls)
                //  - OpenXml Excel files (2007 format; *.xlsx)
                using (var reader = ExcelReaderFactory.CreateReader(stream)) {
                    // 2. Use the AsDataSet extension method
                    dataset = reader.AsDataSet();
                }
            }

            return dataset;
        }`

System.IO.Compression was added when installing ExcelDataReader/ExcelDataReader.DataSet using nuget package.
System.IO.Compression in my reference list is located here: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.IO.Compression.dll
In the properties tab, version is 4.0.0.0 and copy local = true.

I'm using VS 2017 and .NET 4.7.1

How to fix this?

Thanks

**Comment by raphaelaubin** [comment]
I found the issue. In the App.Config of my WPF application there was those line

`<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.Compression" publicKeyToken="b77a5c561934e089" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>`

I changed the version for 4.0.0.0 and now its working.

**Comment by mSaurabh** [comment]
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'ExcelDataReader, Version=3.6.0.0, Culture=neutral, PublicKeyToken=93517dbe6a4012fa' or one of its dependencies. The system cannot find the file specified.
  Source=DataExtractionToolLibrary
  StackTrace:
   at DataExtractionToolLibrary.DataAccess.ExcelHelpers.ExcelConnectorProcessor.ReadExcelFile(String fileName) in C:\Escalations\trunk\Professional Services\Projects in Progress\DataExtractionTool\DataExtractionTool\DataExtractionToolLibrary\DataAccess\ExcelConnectorProcessor.cs:line 34
   at DataExtractionToolLibrary.DataAccess.ExcelConnector.LoadOptimaTDFilesToModel(String fileName) in C:\Escalations\trunk\Professional Services\Projects in Progress\DataExtractionTool\DataExtractionTool\DataExtractionToolLibrary\DataAccess\ExcelConnector.cs:line 25
   at DataExtractionToolUI.ToolDashboard.ExtractButton_Click(Object sender, EventArgs e) in C:\Escalations\trunk\Professional Services\Projects in Progress\DataExtractionTool\DataExtractionTool\DataExtractionToolUI\ToolDashboard.cs:line 103
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at DataExtractionToolUI.Program.Main() in C:\Escalations\trunk\Professional Services\Projects in Progress\DataExtractionTool\DataExtractionTool\DataExtractionToolUI\Program.cs:line 23

**Comment by mSaurabh** [comment]
I am still receiving this error. Any help ?

**Comment by akshayraut-gep** [comment]
@mSaurabh  I am encountering same issue but my test case is different. It works first time and errors out 2nd time. I am looking for a solution. Have you found it yet?

**Comment by alandalegend** [comment]
i found this https://stackoverflow.com/questions/50911924/exceldatareader-3-4-system-io-fileloadexception, 

"I changed the version for 4.0.0.0 and now its working."
