### ISSUE TITLE
Bug:  Index was outside bounds of array on XLS read operation

### ISSUE THREAD

**Issue by dre99gsx** [ExcelDataReader/ExcelDataReader#392]
Found a bug.  Was temped to commit a potential fix, but am short of time to set up project.  When reading  a 2003 XLS file, after a few rows, I get the error.  I traced it down to XlsUnicodeString.cs, 

`IsMultiByte => (_bytes[_offset + 2] & 0x01) != 0;`

I found a specific cell with 12 byte array is getting checked with an offset of 10, thus you get _bytes[10+2] which is obviously outside bounds.  I temporarily did a check:

`_bytes.Length > (_offset + 2) ? (_bytes[_offset + 2] & 0x01) != 0 : false;`

And this cured the problem.  The cell in question is just an empty cell with a large table of many cells.  It was odd how an empty string cell still carried binary array of 12 bytes.

**Comment by andersnm** [comment]
Hi,

Yes, this sounds like a bug. Thanks! Can you provide an XLS to easily reproduce the problem?

**Comment by dre99gsx** [comment]
Wish I could!  Unfortunately, the excel file comes from a 3rd party with proprietary information.  The odd thing is if I open the excel file in the latest version of Excel, and re-save it as a .XLS 97-2003 Workbook, the problem disappears.  The XLS comes from a website which creates these via backend service for viewing data.

**Comment by andersnm** [comment]
Do you know which 3rd party generated the XLS? And could you also paste a stacktrace of the crash?

**Comment by dre99gsx** [comment]
Do not know - it's a closed source and I'm not sure if they are using an open source xls creation tool.  I do know as soon as the first cell with a blank shows up, the index error appears.  

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ExcelDataReader.Core.BinaryFormat.XlsUnicodeString.get_IsMultiByte()
   at ExcelDataReader.Core.BinaryFormat.XlsUnicodeString.GetValue(Encoding encoding)
   at ExcelDataReader.Core.BinaryFormat.XlsWorksheet.ReadSingleCell(XlsBiffStream biffStream, XlsBiffBlankCell cell, Int32 numberFormatIndex)
   at ExcelDataReader.Core.BinaryFormat.XlsWorksheet.ReadNextBlock(XlsBiffStream biffStream, Int32 startRow, Int32 rows)
   at ExcelDataReader.Core.BinaryFormat.XlsWorksheet.ReadWorksheetRows(XlsBiffStream biffStream)+MoveNext()
   at ExcelDataReader.Core.BinaryFormat.XlsWorksheet.ReadRows()+MoveNext()
   at ExcelDataReader.ExcelDataReader`2.Read()
   at DrugRecon.Services.FileService.OpenXLSFile(String fileName, Boolean hasHeader) in C:\dl\Programs\DrugRecon\DrugRecon\Services\FileService.cs:line 208
   at DrugRecon.Services.ImportService.ImportInventory_Podis(String date) in C:\dl\Programs\DrugRecon\DrugRecon\Services\ImportService.cs:line 294
   at DrugRecon.Controllers.APIController.ImportPodis(String date) in C:\dl\Programs\DrugRecon\DrugRecon\Controllers\APIController.cs:line 143
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Let me know if that helps somewhat.

**Comment by andersnm** [comment]
Thanks, that helps somewhat. :) With the provided info I should be able to generate an XLS with a repro, when I get around to it.

**Comment by andersnm** [comment]
Created a repro using hexed.it on Test10x10.xls (from the tests), and replaced two BIFF records at offset 0xcac:

```
fd00 0a00 0000 0000 0f00 0000 0000 (LABELSST, row 0, col 0, xf 15, SST index = 0 -> "col1")
fd00 0a00 0000 0200 0f00 0100 0000 (LABELSST, row 0, col 2, xf 15, SST index = 1 -> "col3")
```

with these

```
0402 0800 0000 0000 0f00 0000 (LABEL, row 0, col 0, xf 15, 0 characters, omitted multibyte flag!)
0402 0c00 0000 0200 0f00 0300 00 414141  (LABEL, row 0, col 0, xf 15, 3 characters, not multibyte, "AAA")
```

The output loads in Excel and throws OOB in ExcelDataReader:
[Test10x10 (4).zip](https://github.com/ExcelDataReader/ExcelDataReader/files/2862138/Test10x10.4.zip)

Assuming the file is otherwise valid, a quick fix is probably something like this:

```diff
--- a/src/ExcelDataReader/Core/BinaryFormat/XlsUnicodeString.cs
+++ b/src/ExcelDataReader/Core/BinaryFormat/XlsUnicodeString.cs
@@ -27,6 +27,11 @@ namespace ExcelDataReader.Core.BinaryFormat
 
         public string GetValue(Encoding encoding)
         {
+            if (CharacterCount == 0)
+            {
+                return string.Empty;
+            }
+
             if (IsMultiByte)
             {
                 return Encoding.Unicode.GetString(_bytes, (int)_offset + 3, CharacterCount * 2);
```

Same must be applied in both XlsShortUnicodeString.cs and XlsUnicodeString.cs.

Not sure yet if this is the best fix. ExcelDataReader still crashes if the BIFF record is smaller than expected, but loads in Excel, f.ex if the string length or string data goes outside the buffer. The above code just ignores the multibyte flag if there are no characters (makes sense in a way).

**Comment by dre99gsx** [comment]
Didn't realize we were counting characters up top, but good catch.  I tested it, and with the _bytes of 12 elements, CharacterCount was indeed 0, and no problems reading the entire excel file.

I think that is a good solution, I'll apply it on my local repo just so I can get going with work, hopefully it can be incorporated in next release.  Thanks for a quick work around.
