### ISSUE TITLE
Receiving this error Could not load file or assembly 'ExcelDataReader, Version=3.6.0.0, Culture=neutral.

### ISSUE THREAD

**Issue by mSaurabh** [ExcelDataReader/ExcelDataReader#476]
Hi,
I need help with this error. 
I am not sure why I am receiving this. I have installed the reference using Nuget and declared in my code.
Can someone please help me with this?
Thanks

System.IO.FileNotFoundException
HResult=0x80070002
Message=Could not load file or assembly 'ExcelDataReader, Version=3.6.0.0, Culture=neutral, PublicKeyToken=93517dbe6a4012fa' or one of its dependencies. The system cannot find the file specified.
Source=DataExtractionToolLibrary
StackTrace:
at DataExtractionToolLibrary.DataAccess.ExcelHelpers.ExcelConnectorProcessor.ReadExcelFile(String fileName) in C:\Escalations\trunk\Professional Services\Projects in Progress\DataExtractionTool\DataExtractionTool\DataExtractionToolLibrary\DataAccess\ExcelConnectorProcessor.cs:line 34
at DataExtractionToolLibrary.DataAccess.ExcelConnector.LoadOptimaTDFilesToModel(String fileName) in C:\Escalations\trunk\Professional Services\Projects in Progress\DataExtractionTool\DataExtractionTool\DataExtractionToolLibrary\DataAccess\ExcelConnector.cs:line 25
at DataExtractionToolUI.ToolDashboard.ExtractButton_Click(Object sender, EventArgs e) in C:\Escalations\trunk\Professional Services\Projects in Progress\DataExtractionTool\DataExtractionTool\DataExtractionToolUI\ToolDashboard.cs:line 103
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Button.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.Run(Form mainForm)
at DataExtractionToolUI.Program.Main() in C:\Escalations\trunk\Professional Services\Projects in Progress\DataExtractionTool\DataExtractionTool\DataExtractionToolUI\Program.cs:line 23

**Comment by andersnm** [comment]
Hi,

Unfortunately this problem is very general and typically specific to your environment/machine. For some reason your program cannot find the ExcelDataReader.dll, while one would expect VS to bundle it correctly without any problems.

Some random ideas that might or might not work, assuming you are running the program from VS:

- exit VS, delete the bin and obj folders, restart VS, rebuild and try again
- remove the package reference from the csproj (or packages.config?) and add it back again (also exit VS before/after could help)
- check if any other projects or dependencies in your solution depend on an older version of ExcelDataReader and upgrade those too (or remove, if you can)
- check if your app.config declares a broken assembly binding redirect for ExcelDataReader and remove it, then try the first and second suggestions again

If nothing works, do share your VS version and the first line of your csproj (i.e whether you are using an "SDK style project" or "old project" file). That would at least help narrowing down the problem a bit

**Comment by mSaurabh** [comment]
Thank you so much for your prompt reply. I actually figured it out and yes it was system related. So for anyone who come across this error you have to right click on your references --> Nuget Manager --> Search For ExcelReader and install it.
Also I changed my package.config to  packagereference to avoid any post publish errors.

Here's how to do that : https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference

Thanks,
Saurabh
