### ISSUE TITLE
JObject.FromObject on xlsx file throws "Can not add Newtonsoft.Json.Linq.JProperty to Newtonsoft.Json.Linq.JProperty"

### ISSUE THREAD

**Issue by MathieuLep** [ExcelDataReader/ExcelDataReader#665]
I'm using an xlsx file with custom format:
In a middle of cells with data I've added one cell with only a single quote.

![image](https://github.com/ExcelDataReader/ExcelDataReader/assets/126441072/85fdb98e-e5a0-4e46-bd82-930d36a20542)

Right now here is my code to read the file:

`
using var ms = new MemoryStream();
            await file.CopyToAsync(ms);

            using var reader = ExcelReaderFactory.CreateReader(ms);
            var result = reader.AsDataSet(new ExcelDataSetConfiguration
            {
                ConfigureDataTable = _ => new ExcelDataTableConfiguration
                {
                    UseHeaderRow = true,
                    FilterColumn = (columnReader, columnIndex) =>
                    {
                        if (filterColumnWithEmptyHeaders)
                            return !string.IsNullOrWhiteSpace(columnReader.GetString(columnIndex));
                        return true;
                    }
                },
                UseColumnDataType = false
            });

            if (useStringDataTypeForAllFields)
            {
                result = result.SetStringDataTypeToAllFields();
            }

            var jsonSerializerSettings = new JsonSerializerSettings()
            {
                Converters = new JsonConverter[] { new EmptyStringToNullConverter(trimMultiValues)},
                NullValueHandling = NullValueHandling.Ignore,
                DefaultValueHandling = DefaultValueHandling.Ignore,
            };

            var serializer = JsonSerializer.Create(jsonSerializerSettings);
            var jObject = JObject.FromObject(result, serializer);
`

I got the following error:

> System.ArgumentException: Can not add Newtonsoft.Json.Linq.JProperty to Newtonsoft.Json.Linq.JProperty.
   at Newtonsoft.Json.Linq.JContainer.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JProperty.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.TryAddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddAndSkipParentCheck(JToken token)
   at Newtonsoft.Json.Linq.JTokenWriter.AddParent(JContainer container)
   at Newtonsoft.Json.Linq.JTokenWriter.WritePropertyName(String name)
   at Newtonsoft.Json.Converters.DataTableConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Converters.DataSetConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JObject.FromObject(Object o, JsonSerializer jsonSerializer)

If the ' is in the is on a row without data, it works fine.
I'm currently using version 3.6.0 but I tried the prerelease 3.7.0-develop00385 without any success.

Any idear how to avoid this issue?

**Comment by andersnm** [comment]
Hi,

The stack trace points to Newtonsoft.Json. From your description I suppose it bugs if a cell contains a single quote. Altho can't reproduce it https://dotnetfiddle.net/bzXzBV

Suggest to check the contents of the dataset and see if you can reduce and reproduce the problem without ExcelDataReader.
